#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo "Downloading latest Atom master build..."
mkdir atom
artifact_url=$(script/last-atom-master-artifact-url.js)
wget --tries=42 --retry-connrefused --output-document="atom.zip" $artifact_url
unzip -q atom.zip -d atom
export ATOM_APP_NAME="Atom.app"
export ATOM_SCRIPT_NAME="atom.sh"
export ATOM_SCRIPT_PATH="./atom/${ATOM_APP_NAME}/Contents/Resources/app/atom.sh"
export ATOM_PATH="./atom"
export APM_SCRIPT_PATH="./atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin/apm"
export NPM_SCRIPT_PATH="./atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin/npm"
export PATH="${PATH}:${TRAVIS_BUILD_DIR}/atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin"

echo "Using Atom version:"
"${ATOM_SCRIPT_PATH}" -v

echo "Using APM version:"
"${APM_SCRIPT_PATH}" -v

echo "Using Node version:"
node --version

echo "Using NPM version:"
npm --version

echo "Downloading package dependencies..."
"${APM_SCRIPT_PATH}" install

echo "Running specs..."
"${ATOM_SCRIPT_PATH}" --test test

exit
