name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        ATOM_CHANNEL: ['stable','beta','dev']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Create DB
        run: |
          sudo service postgresql start
          sudo su postgres -c 'createuser -P --superuser runner'
          createdb teletype-test
      - name: Build Atom
        env:
          TRAVIS_OS_NAME: 'linux'
        run: |
          curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
          chmod u+x build-package.sh
          ./build-package.sh
